--- # Global --------------------------

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .venv
    - .poetry

stages:
  - tests

# Jobs templates ------------------

tests: &test
  stage: tests
  image: python:3.9
  # install dependencies
  before_script:
    - if [ ! -e .poetry/bin/poetry ] ; then
    # Poetry is not installed (note: $HOME tells get-poetry.py were to install)
    -   curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | HOME=$PWD python -
    - fi
    - export PATH=$PWD/.poetry/bin:$PATH
    - poetry config --local cache-dir $PWD/.poetry/cache
    - poetry config --local virtualenvs.in-project true
    - poetry --version
    - poetry install --no-interaction
  script:
    - poetry run pytest --cov-report=xml
  artifacts:
    reports:
      cobertura: coverage.xml
